const INVALID_DATA = 400;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;
const CONFLICT_ERROR = 409;
const FORBIDDEN = 403;
const UNAUTHORIZED = 401;

module.exports = {
  INVALID_DATA,
  NOT_FOUND,
  SERVER_ERROR,
  CONFLICT_ERROR,
  FORBIDDEN,
  UNAUTHORIZED,
};
